### ISSUE TITLE
sharedid.org web site optout tied to Rubicon

### ISSUE THREAD

**Issue by dmdabbs** [prebid/shared-id#22]
Not sure whether this is the right place for this. 

https://sharedid.org/... 

- links to an optout preferences page implemented in rubiconproject.com domain (so the cookie set is inaccessible to sharedid.org service)
- References "Rubicon Project..." &c...
- has no link to Prebid or Prebid privacy policy (presuming it addresses sharedid.org services/processing)
- If the NAI link is retained, consider also links for the user optout portal by DAA or EDAA for EU. 

Less important, but consult with your counsel,
Regarding PB's IAB EU participation, TCF require vendors to make public attestation about their TCF participation including vendor id &c in their privacy policy. See [Policy 11.2](https://iabeurope.eu/iab-europe-transparency-consent-framework-policies/#_________Chapter_III_Policies_for_Vendors___________) .

**Comment by jdwieland8282** [comment]
Hi @dmdabbs working on bullet #1, and #3.  2 and 4 are moot bc of the changes we will implement in 1.  I'm working on getting the sharedid privacy policy linked to sharedid.org and included in the dev docs. thanks for bringing this up.

**Comment by dmdabbs** [comment]
Cleaned up long ago.
