### ISSUE TITLE
How do users initiate opt-out requests?

### ISSUE THREAD

**Issue by wqi1972** [prebid/shared-id#3]
@jdwieland8282 
Does it mean all publishers website integrate Shared-Id need provide a link which lead users to a Shared-Id opt-out UI? (similar concept as CCPA CMP)

**Comment by jdwieland8282** [comment]
We are trying to prevent such a scenario @wqi1972 , we believe that enforcing that is unworkable for all pubs. Rather, today sharedid leverages the 3rd party cookie to persist optout across domains.  In the future we'll need a replacement for the 3rd party cookie. Browsers have not picked a standard yet, safari's choice seems to be the storage access api, Chrome is exploring trust tokens. I suspect optout will need to support browser detection, then do the appropriate thing.
