### ISSUE TITLE
User optout, then optin, but get stuck in opt out status

### ISSUE THREAD

**Issue by wqi1972** [prebid/shared-id#7]
Inside PBJS, I integrate sharedId user Id module.
In following test case, it fails
1) Visit publisher website. (shared id set properly)
2) opt out (https://id.sharedid.org/optout) . (opt out cookie set up correctly)
3) Visit publisher website. (shared id get removed from pbjs.getUserIds() correctly)
4) opt in (https://id.sharedid.org/optin). (opt out cookie removed correctly)
5) Visit publisher website. (Shared id suppose come back, but it doesn't)

I think the issue is: 
A) inside PBJS sharedIdSystem.js, it doesn't check if shared id is opt out value or not, it simply saves opt out value into cookie at step 3).
B) inside SyncSharedIdHandler.java, it has logic
```
        if (StringUtils.isBlank(userId)) {
            dataContext.setUserId(newSharedId);
            dataContext.setIsSyncedUserId(true);
            routingContext.next();
            return;
        }
```
In step 5), since id inside sharedid.org domain is blank, the code exists from that block.

We can either update logic for A) or B) to fix the issue. 
I think the better option is to change logic A) inside PBJS. The fix is to change sharedIdSystem.js so it has similar logic as pubCommonIdSystem.js: inside idGenerationCallback callback function, when the user module get shared id value, if the value is opt out value, instead of save the value inside cookie, it delete the cookie.

@coryhammon1, @jdwieland8282, @bretg what do you think?

**Comment by jdwieland8282** [comment]
Thanks for bringing this to our attention @wqi1972 let us take a look

**Comment by yava-ua** [comment]
@wqi1972 working on it. I'll fix it in prebid.js
Will open a pr once have all the tests ready

**Comment by wqi1972** [comment]
Great!

**Comment by wqi1972** [comment]
Not an issue. On next user sync on publisher's site, a new Shared-Id will be created. It was a false alert.
